version: '3'
services:
  back:
    container_name: back
    build: ./backend
    ports:
      - "5000:5000"
    links:
    - mongodb
  mongodb:
    container_name: mongodb
    image: mongo:4.0.8
  front:
    container_name: front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=8080
