
version: '3'

services:

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - server
